import 'package:flutter/material.dart';

import 'models/animal_category.dart';
import 'models/animal_in_category.dart';

List<AnimalCategory> DUMMY_ANIMALS_CATEGORY = [
  AnimalCategory(
    id: 'c1',
    title: 'Dogs',
    color: Colors.green[100] as Color,
  ),
  AnimalCategory(
    id: 'c2',
    title: 'Cats',
    color: Colors.green[200] as Color,
  ),
  AnimalCategory(
    id: 'c3',
    title: 'Rabbits',
    color: Colors.green[300] as Color,
  ),
  AnimalCategory(
    id: 'c4',
    title: 'Birds',
    color: Colors.green[400] as Color,
  ),
  AnimalCategory(
    id: 'c5',
    title: 'Aquatic animals',
    color: Colors.green[500] as Color,
  ),
  AnimalCategory(
    id: 'c6',
    title: 'Others',
    color: Colors.green[600] as Color,
  ),
];

List<Animal> DUMMY_ANIMALS = [
  Animal(
    id: 'a1',
    category: 'c1',
    name: 'name1',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a2',
    category: 'c1',
    name: 'name2',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a3',
    category: 'c1',
    name: 'name3',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a4',
    category: 'c1',
    name: 'name4',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a5',
    category: 'c2',
    name: 'name5',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a6',
    category: 'c2',
    name: 'name6',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a7',
    category: 'c2',
    name: 'name7',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a8',
    category: 'c2',
    name: 'name8',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a9',
    category: 'c3',
    name: 'name9',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a10',
    category: 'c3',
    name: 'name10',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a11',
    category: 'c3',
    name: 'name11',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a12',
    category: 'c3',
    name: 'name12',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a13',
    category: 'c4',
    name: 'name13',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a14',
    category: 'c4',
    name: 'name14',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a15',
    category: 'c4',
    name: 'name15',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a16',
    category: 'c4',
    name: 'name16',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a17',
    category: 'c5',
    name: 'name17',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a18',
    category: 'c5',
    name: 'name18',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a19',
    category: 'c5',
    name: 'name19',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a20',
    category: 'c5',
    name: 'name20',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a21',
    category: 'c6',
    name: 'name21',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a22',
    category: 'c6',
    name: 'name22',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a23',
    category: 'c6',
    name: 'name23',
    description: 'soething',
    imageUrl: '',
  ),
  Animal(
    id: 'a24',
    category: 'c6',
    name: 'name24',
    description: 'soething',
    imageUrl: '',
  ),
];
